import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const js = await readFile(new URL('../content/content.js', import.meta.url), 'utf8');
const css = await readFile(new URL('../content/content.css', import.meta.url), 'utf8');
const background = await readFile(new URL('../background.js', import.meta.url), 'utf8');
const agent = await readFile(new URL('../content/page-agent.js', import.meta.url), 'utf8');
const manifest = JSON.parse(await readFile(new URL('../manifest.json', import.meta.url), 'utf8'));

assert.match(js, /id="bili-dl-list-quality-pills"/);
assert.match(js, /class="bili-dl-cover-column"[\s\S]*id="bili-dl-download-cover"/);
assert.match(js, /async function downloadCover\(\)[\s\S]*statusEl\.classList\.add\('hidden'\)/);
assert.doesNotMatch(js, /showStatus\('success', '已开始下载封面'\)/);
assert.match(js, /aria-selected="true"/);
assert.match(js, /event\.key !== 'Escape'/);
assert.match(js, /id="bili-dl-list-queue-cancel"/);
assert.match(js, /id="bili-dl-queue-pause"/);
assert.match(js, /id="bili-dl-list-queue-pause"/);
assert.match(js, /id="bili-dl-list-job-list"/);
assert.match(js, /const taskUi = \{[\s\S]*video:[\s\S]*list:/);
assert.doesNotMatch(js, /insertBefore\(/, '切换 Tab 不能移动单视频或列表的任务节点');
assert.match(js, /const TASK_STATE = Object\.freeze/);
assert.match(js, /const DOWNLOAD_PREFS_KEY/);
assert.match(js, /async function loadDownloadPrefs\(/);
assert.match(js, /\[DOWNLOAD_PREFS_KEY\]: \{ format: selectedFormat, qn: selectedQn, qualityStrategy, filenameStyle \}/);
assert.match(js, /id="bili-dl-filename-style"/);
assert.match(js, /id="bili-dl-filename-preview"/);
assert.match(js, /function buildFilenameBase\(/);
assert.match(js, /function formatTaskTimings\(/);
assert.match(js, /function openBrowserDownloads\(/);
assert.match(js, /job\.scope === 'list'\) setDownloadMode\('list'\)\.then\(\(\) => startListDownload/);
assert.match(js, /function createDownloadTask\(/);
assert.match(js, /function classifyDownloadError\(/);
assert.match(js, /function showRetryableDownloadError\(/);
assert.match(js, /data-sheet="diagnostics"/);
assert.match(js, /function redactDiagnosticText\(/);
assert.match(js, /debugEntries\.length > 100/);
assert.match(js, /key === 'diagnostics'/);
assert.match(js, /复制诊断报告/);
assert.match(js, /retry\.textContent = '重试此任务'/);
assert.match(js, /id="bili-dl-list-retry-failed"/);
assert.match(js, /async function startListDownload\(retryTasks = null\)/);
assert.match(js, /listRetryFailedBtn\.onclick = \(\) => startListDownload\(lastListFailures\)/);
assert.match(js, /scope: 'list',[\s\S]*format: 'mp4'/);
assert.match(js, /const wasDowngraded = !requested/);
assert.match(js, /job\.requestedQn = qn/);
assert.match(js, /清晰度降级/);
assert.match(css, /#bili-dl-list-queue-cancel/);
assert.match(css, /\.bili-dl-cover-column/);
assert.match(css, /\.bili-dl-cover-download/);
assert.match(css, /\.bili-dl-status-action/);
assert.match(background, /BILI_DL_OPEN_DOWNLOADS/);
assert.ok(!manifest.permissions.includes('notifications'));
assert.match(agent, /safeFilename\(filenameBase \|\| title, 'video'\)/);
assert.match(agent, /safeFilename\(filenameBase \|\| title, 'audio'\)/);
assert.match(js, /queueLabelEl\.textContent = '自动依次下载分 P…'/);
assert.match(js, /const workers = 1;/, '分 P 队列必须自动串行，不能重新引入并发下载');
assert.match(js, /function toggleEntireQueuePause\(\)/);
assert.match(js, /queuePause\.textContent = queuePaused \? '继续全部' : '暂停全部'/);
assert.match(js, /await waitWhileQueuePaused\(\);/);

console.log('task UI regression checks passed');
