import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const js = await readFile(new URL('../content/content.js', import.meta.url), 'utf8');
const css = await readFile(new URL('../content/content.css', import.meta.url), 'utf8');
const background = await readFile(new URL('../background.js', import.meta.url), 'utf8');
const agent = await readFile(new URL('../content/page-agent.js', import.meta.url), 'utf8');
const manifest = JSON.parse(await readFile(new URL('../manifest.json', import.meta.url), 'utf8'));

assert.match(js, /id="bili-dl-list-quality-pills"/);
assert.match(js, /class="bili-dl-cover-column"[\s\S]*id="bili-dl-download-cover"/);
assert.match(js, /async function downloadCover\(\)[\s\S]*statusEl\.classList\.add\('hidden'\)/);
assert.doesNotMatch(js, /showStatus\('success', '已开始下载封面'\)/);
assert.match(js, /aria-selected="true"/);
assert.match(js, /event\.key !== 'Escape'/);
assert.match(js, /id="bili-dl-list-queue-cancel"/);
assert.match(js, /id="bili-dl-queue-pause"/);
assert.match(js, /id="bili-dl-list-queue-pause"/);
assert.match(js, /id="bili-dl-list-job-panel" class="bili-dl-job-panel hidden"/);
assert.match(js, /id="bili-dl-list-queue-actions" class="bili-dl-job-panel-queue hidden"/);
assert.match(js, /id="bili-dl-list-job-list"/);
assert.match(js, /jobPanel: listJobPanelEl/);
assert.match(js, /ui\.jobPanel\?\.classList\.toggle\('hidden', !\(hasJobs \|\| showQueueControls\)\)/);
assert.match(js, /id="bili-dl-toggle" title="打开下载助手" aria-label="打开下载助手" aria-expanded="false"/);
assert.match(js, /if \(isOpen\) \{[\s\S]*closeMenuShell\(\);[\s\S]*return;/);
assert.match(js, /toggleBtn\.setAttribute\('aria-expanded', 'true'\)/);
assert.match(js, /const taskUi = \{[\s\S]*video:[\s\S]*list:/);
assert.doesNotMatch(js, /insertBefore\(/, '切换 Tab 不能移动单视频或列表的任务节点');
assert.match(js, /const TASK_STATE = Object\.freeze/);
assert.match(js, /const DOWNLOAD_PREFS_KEY/);
assert.match(js, /async function loadDownloadPrefs\(/);
assert.match(js, /\[DOWNLOAD_PREFS_KEY\]: \{ format: selectedFormat, qn: selectedQn, qualityStrategy, streamPreference, listDownloadKind \}/);
assert.match(js, /id="bili-dl-stream-preference"/);
assert.match(js, /高码率优先（推荐）/);
assert.match(js, /streamPreference: streamSelection/);
assert.match(js, /streamPreference: queueStreamPreference/);
assert.doesNotMatch(js, /id="bili-dl-filename-style"/);
assert.match(js, /id="bili-dl-filename-preview"/);
assert.match(js, /data-sheet="settings"/);
assert.match(js, /data-sheet="plugins"/);
assert.match(js, /bili-dl-footer-plugins/);
assert.match(js, /bili-dl-footer-notice/);
assert.match(js, /bili-dl-footer-action/);
assert.match(js, /相关插件/);
assert.match(js, /class="bili-dl-footer-links">\s*<button[^>]*bili-dl-footer-plugins[^>]*data-sheet="plugins"[\s\S]*?<button[^>]*bili-dl-footer-notice[^>]*data-sheet="notice"/);
assert.match(css, /\.bili-dl-footer-plugins/);
assert.match(css, /display: contents;/);
assert.doesNotMatch(js, /data-sheet="coop">开发合作<\/button>/);
assert.match(js, /function appendCoopSection\(/);
assert.match(js, /fillNoticeBody\(infoBody, data, remoteContent\.coop\)/);
assert.match(css, /\.bili-dl-notice-coop/);
assert.doesNotMatch(js, /class="bili-dl-footer-links">[\s\S]{0,400}常见问题/);
assert.doesNotMatch(js, /class="bili-dl-footer-links">[\s\S]{0,400}隐私政策/);
assert.match(js, /function fillSettingsSheet\(/);
assert.match(js, /Could not establish connection\|Receiving end does not exist/);
assert.match(js, /扩展已更新，请刷新当前 B 站页面后重试/);
assert.match(css, /#eef0f3/);
assert.match(css, /\.bili-dl-footer-meta::after/);
assert.match(css, /\.bili-dl-footer-meta::after[\s\S]{0,80}display:\s*none/);
assert.match(js, /function buildFilenameBase\(/);
assert.match(js, /filenameTemplate/);
assert.doesNotMatch(background, /BILI_DL_OPEN_OPTIONS/);
assert.ok(!manifest.options_ui);
assert.ok(manifest.content_scripts.some((entry) => Array.isArray(entry.js) && entry.js.includes('shared/filename.js')));
assert.match(js, /function formatTaskTimings\(/);
assert.match(js, /function openBrowserDownloads\(/);
assert.match(js, /job\.scope === 'list'\) setDownloadMode\('list'\)\.then\(\(\) => startListDownload/);
assert.match(js, /function createDownloadTask\(/);
assert.match(js, /function classifyDownloadError\(/);
assert.match(js, /function showRetryableDownloadError\(/);
assert.match(js, /data-sheet="diagnostics"/);
assert.match(js, /function redactDiagnosticText\(/);
assert.match(js, /debugEntries\.length > 100/);
assert.match(js, /key === 'diagnostics'/);
assert.match(js, /复制诊断报告/);
assert.match(js, /retry\.textContent = '重试此任务'/);
assert.match(js, /id="bili-dl-list-retry-failed"/);
assert.match(js, /id="bili-dl-list-download-kind"/);
assert.match(js, /data-list-download-kind="video">仅视频/);
assert.match(js, /data-list-download-kind="audio">仅音频/);
assert.match(js, /data-list-download-kind="both">视频\+音频/);
assert.match(js, /function setListDownloadKind\(/);
assert.match(css, /\.bili-dl-list-download-kind/);
assert.match(js, /async function startListDownload\(retryTasks = null\)/);
assert.match(js, /listStartBtn\.disabled = !count \|\| queueRunning/, '队列运行时保留主下载按钮但禁止再次启动');
assert.match(js, /listRetryFailedBtn\.onclick = \(\) => startListDownload\(lastListFailures\)/);
assert.match(js, /scope: 'list',[\s\S]*format: outputFormat/);
assert.match(js, /wasDowngraded = !requested/);
assert.match(js, /job\.requestedQn = qn/);
assert.match(js, /清晰度降级/);
assert.match(css, /\.bili-dl-job-panel \{/);
assert.match(css, /\.bili-dl-job-panel-queue \{/);
assert.match(js, /class="bili-dl-action-btn danger">取消整队/);
assert.match(js, /bili-dl-job-cancel-inline/);
assert.match(js, /is-queue-running/);
assert.match(css, /\.bili-dl-list-body\.is-queue-running \.bili-dl-list-items/);
assert.doesNotMatch(css, /#bili-dl-list-select-all\[aria-pressed="true"\] \{ background: #111/);
assert.match(css, /\.bili-dl-cover-column/);
assert.match(css, /\.bili-dl-cover-download/);
assert.match(css, /\.bili-dl-status-action/);
assert.match(background, /BILI_DL_OPEN_DOWNLOADS/);
assert.ok(!manifest.permissions.includes('notifications'));
assert.match(agent, /safeFilename\(filenameBase \|\| title, 'video'\)/);
assert.match(agent, /safeFilename\(filenameBase \|\| title, 'audio'\)/);
assert.match(agent, /function selectVideoStream\(/);
assert.match(agent, /streamPreference === 'compatible'/);
assert.match(agent, /estimateDownloadSize\(aid, cid, qn, durationSec, streamPreference = 'high-bitrate'\)/);
assert.match(css, /\.bili-dl-stream-preference-row/);
assert.match(js, /queueLabelEl\.textContent = '自动依次下载分 P…'/);
assert.match(js, /const workers = 1;/, '分 P 队列必须自动串行，不能重新引入并发下载');
assert.match(js, /function toggleEntireQueuePause\(\)/);
assert.match(js, /queuePause\.textContent = queuePaused \? '继续全部' : '暂停全部'/);
assert.match(js, /await waitWhileQueuePaused\(\);/);

console.log('task UI regression checks passed');
